### ISSUE TITLE
Formulaire type

### ISSUE THREAD

**Issue by l3ibi** [lucien-chastan/oblyk#2]
Donner la possibilité d'imprimer un formulaire type à remplir sur le spot afin de pouvoir les ajouter ensuite sur le site d'oblyk. 

| Nom | Hauteur | Nombre de points | Type de relai | Inclinaison | A vue / Après travail / Projet |

**Comment by lucien-chastan** [comment]
C’est une bonne idée,  
Ça pourrai être un fichier PDF avec des champs éditables, comme ça on peut le compléter avec un smartphone (si on a pas de réseau pour directement aller sur oblyk) ou l’imprimer.

Il faut que je trouve un endroit ou mettre ce fichier à télécharger ...

____

Approximative English translation :

It’s a good idea
it could be a PDF file with editable fields, like this one can complete the file with a smartphone (if we have no telephone network to go to Oblyk web site) or print it.

I have to find a place to put this file for download ...

**Comment by l3ibi** [comment]
I'm sorry, I'm not developer, but one day I'll take the time to install laravel and see how it work to make pull request :-) .

**Comment by lucien-chastan** [comment]
Don't worry, I'll find a corner to put that ; )

Laravel is hard to install for a no-developer, it has many dependences and required tools for run it, is not a simple web site, but it helps a lot for the development !

You speak French ? for the moment the new version of oblyk isn't translated in English. 
In some time, I'll search someone to help me translate it

**Comment by l3ibi** [comment]
Yes, I speak French, it's my mother tongue :-). I just take the habits to use English to write on github. My English is not good. 
For the moment I'll contrib with complete the climbing route that I know on your web site.

**Comment by lucien-chastan** [comment]
Ok ; ) thanks a lot for your contributions
