### ISSUE TITLE
Fix Gap Grade

### ISSUE THREAD

**Issue by lucien-chastan** [lucien-chastan/oblyk#48]
If in a crag there's a projected path
Then the min / max counter of the grades look like this: "rating of ? to 7a"
It would be necessary that "?" is not taken into account

**Comment by mjamroz** [comment]
if is not a problem for you, could you show me the links where this bug show up?

**Comment by lucien-chastan** [comment]
For example : [Russan](https://oblyk.org/en/site-escalade/75/russan) (beautiful crag!), you have a routes with grade is *"?"*, but *"?"* is equal to 0 in gradeToVal function.
When gap_grade is calculate, so 0 is a min value of crag ... whereas you have 4b in Russan
It would have to display 4b->9? for Russan

![russan in oblyk map](https://screenshotscdn.firefoxusercontent.com/images/465b7965-9207-44c1-876a-3370be74310d.png)

**Comment by lucien-chastan** [comment]
the calculations are here : 
- [majInformation](https://github.com/lucien-chastan/oblyk/blob/master/app/Sector.php#L54) in Sector Model
- [majInformation](https://github.com/lucien-chastan/oblyk/blob/master/app/Crag.php#L113) in Crag Model 
It's not very beautiful nor very optimized what I did... I must not have been in very good health that day...
I think we should refactor this function and maybe trigger it into an observation
