### ISSUE TITLE
Add localization in map

### ISSUE THREAD

**Issue by lucien-chastan** [lucien-chastan/oblyk#49]
On [Oblyk map](https://oblyk.org/carte-des-falaises) add localization button

**Comment by mjamroz** [comment]
do you mean button to run browser localization dialog and focus/zoom on the coordinates taken from browser?

**Comment by mjamroz** [comment]
![screenshot_2018-12-05_21-39-11](https://user-images.githubusercontent.com/505646/49542551-39ba4a80-f8d6-11e8-90e3-8c19c89d0d50.png)
i almost finished bottle of vine then sorry if i fucked up in the code. anyway it works on my machine (this, and #63 )
