### ISSUE TITLE
Indoor Sendliste and inside Guidebook

### ISSUE THREAD

**Issue by lucien-chastan** [lucien-chastan/oblyk#54]
This is the big evolution to do, which requires reflection, a lot of code, and will surely impact different oblyk location.

Objective: to be able to keep a indoors sendlist and set up an inside guidebook

Important points :
- there are different difficulty systems (colour, rating)
- different type of climbing (sport climbing, boulder, pan?)
- it must be manageable by the gym, or by the community
- one must be able to note "wild" crosses if the guidebook is maintained by nobody
think of dis-equipment

This is a very recurring demand from users

**Comment by flodef** [comment]
Hey Lucien, what about this feature ? Is it a work in progress or is it abandoned ?
It could be great to use it. I don't understand why is it so difficult to add and what is so different from outdoor sendlist ?
Thanks anyway for this great tool !!
