### ISSUE TITLE
map under firefox doesnt display

### ISSUE THREAD

**Issue by mjamroz** [lucien-chastan/oblyk#60]
by some reason i cant see the map layer under firefox 61.0.2:
![screenshot_2018-09-06_10-26-59](https://user-images.githubusercontent.com/505646/45144808-72effb00-b1bf-11e8-9cda-480666969113.png)

for chrome it works fine.

However i remember few days ago (i mean, like 2 weeks ago) it worked fine.

**Comment by lucien-chastan** [comment]
Ha ... Probably because the tiles are loaded un http, and not https.
Firefox must be blocking this

**Comment by lucien-chastan** [comment]
Hi !

Can you re-test in beta version ? [beta.map](https://beta.oblyk.org/fr/carte-des-falaises)

I have switch to https for load map tiles, it's possible that the problem comes from there (refresh your cache for reload js script)

Have a nice day

**Comment by mjamroz** [comment]
sorry for delay, i was in ailefroide :P. anyway, i wanted to find credentials to beta and can't (my comp. is messy). MAybe you could send me again by oblyk messenger?

**Comment by lucien-chastan** [comment]
Hi
I sent you the beta credentials in oblyk messenger

**Comment by mjamroz** [comment]
Thanks! Got it!

and i checked. And it works. First of all - the "lock" just on the left of address bar is now green (not yellow warning sign like before) which is nice in beta.

And the problem with lack of map layers was my fault - i had "privacy badger" which blocked "osm.org". When i disabled "privacy badger", map layers displays correctly in both beta and prod (but in prod we have yellow lock icon as in attached screenshot above).

Since it was not related with oblyk but my crazy firefox plugins, i would close this issue.
