### ISSUE TITLE
Adding sector / routes not available

### ISSUE THREAD

**Issue by LaurentBerder** [lucien-chastan/oblyk#61]
I created a [new crag](https://oblyk.org/fr/site-escalade/2416/la-pointe-de-primel#voies), and uploaded guidebooks, but can't add any routes or sectors.
The webpage indicates 

> There are no routes or sectors posted on this crag yet.
Use the button "+" at the bottom right to add a sector

But there is no "+" sign.

**Comment by mjamroz** [comment]
just in case - in my browser (firefox 62.0) it works. Are you log-in?

![screenshot_2018-09-20_18-52-47](https://user-images.githubusercontent.com/505646/45834039-7e3a3f00-bd06-11e8-8527-7918e49162f0.png)

(but lets wait for Lucien - he is the oblyk guru)

**Comment by lucien-chastan** [comment]
Hi Laurent,

You were connected ?
Did you see the button really very far down on the right ?

In any case, it's not very understandable, there must have been a button underneath this message

**Comment by LaurentBerder** [comment]
​Salut Lucien,
I guess I'd been disconnected, as now that I'm trying again, I do see it...
Sorry for the bother then.

**Comment by lucien-chastan** [comment]
it doesn't matter:)
It's not very clear, we should improve it.
