### ISSUE TITLE
Add "By climb type" in "My Crosses"

### ISSUE THREAD

**Issue by lucien-chastan** [lucien-chastan/oblyk#63]
in addition to the other tabs, add a tab for sorting crosses by type of climbing

**Comment by lucien-chastan** [comment]
[screen shot](https://screenshotscdn.firefoxusercontent.com/images/5ed56d56-f5d6-43f8-a7ad-acace3b40553.png)

**Comment by mjamroz** [comment]
hi @lucien-chastan   i broke rib so i could do something here xD. I cannot display screenshot for this tab. Do you mean having some checkboxes or separate tabs by climb type?

**Comment by lucien-chastan** [comment]
Damn, my screen shot is expired :(
here is my new beautiful capture!
![cross-by-type](https://user-images.githubusercontent.com/22887119/49535525-b3493d00-f8c4-11e8-9a10-2c7d9a29403e.png)

Sorry for your rib, but happy to see you again !
