### ISSUE TITLE
map do not load

### ISSUE THREAD

**Issue by mjamroz** [lucien-chastan/oblyk#67]
some small typo:

![screenshot_2019-01-13_09-08-50](https://user-images.githubusercontent.com/505646/51083024-eaf0a380-1712-11e9-812b-2f39a6bbfd31.png)

**Comment by lucien-chastan** [comment]
Yes ! thanks,
I hadn't seen.

Typo comes from the words "Halle sportive de l'UTT" with "`" character
I change climbing gym name, but I haven't fixed the problem in the code yet.
