### ISSUE TITLE
Allow to input one or several routes at ones via an input file

### ISSUE THREAD

**Issue by P-Bouche** [lucien-chastan/oblyk#68]
It would be nice to be able to import a csv file with a predefined format which allows to create one or several routes with their crag and sector.

**Comment by mjamroz** [comment]
@lucien-chastan  - do you agree with that? 
If yes - it could be like importing csv thru web browser, selecting which columns relates which data? Or maybe rather as an artisan command?
I could work on this feature, only we would need to define minimal required input

crag / sector / route name / grade  would be required, or something else?

then maybe - after parsing user/admin would need to select gps on map to relate with crag(s), and/or sector(s).

@P-Bouche would you prepare some example/fake input data for tests when we agree about kind of data?

**Comment by P-Bouche** [comment]
I would definitely be ready to provide some test data.

**Comment by lucien-chastan** [comment]
Hi! I'm agree with that.

Maybe to avoid the problem of GPS and double crag we could import the routes as well as one crag at the same time?

We select a cliff (or create it), on the cliff page we add a button "Import tracks from a csv file".

For each line oblyk looks if the sector exists, if not it creates it, if yes it uses it, then it looks if in the sector the route exists, if yes it does nothing, if not it creates it. 

For the columns it would be necessary:
- **sector name**
- **road name**
- **type of road** (track, block, deepwater, etc.)
- **grad** (separated by a `|` if there are several lengths)
- height (separated by a `|` if there are several lengths)[optional]
- opener[optional]
- opening date[optional]

I don't know if it is necessary to allow the import of the type of anchors, the type of point, the inclination, etc.?

@P-Bouche Do you have a lot of routes to import like that?

**Comment by P-Bouche** [comment]
@lucien-chastan I was thinking of this function while inputting Fontainebleau's bloc circuits but it can apply to cases where you have a crag's topo as well.

I would suggest to check for cliffs name and nearby location if possible because I have seen some duplicates when using oblyk.

In case of an already existing route it would be nice to **compare** the grades and/or other fields and give a feedback to the user so he can edit the appropriate fields.


I would be keen on helping you guys coding features since I have a programming background however I have very little knowledge about web development (I work on embedded systems).

**Comment by bohwaz** [comment]
Would be great and there is a PR, can we get that merged? :)
