### ISSUE TITLE
registration

### ISSUE THREAD

**Issue by mjamroz** [lucien-chastan/oblyk#72]
i got info from friend she cannot register, and i tested it - during registration im getting 500 error when posting to /register

**Comment by lucien-chastan** [comment]
Yes I see that
This is because the validation does not pass (same name as another?)
Except it gives me a 500 error, it's been since I migrated to laravel 5.7
It drives me crazy, I can't fix the problem!

**Comment by mjamroz** [comment]
ca craint! 
and debug on doesn't print anything interesting to logfile?

**Comment by lucien-chastan** [comment]
Sorry for the response time : /

Yes, ça craint grave!

You can test it locally, try to create an account with a name that already exists you will have an error 500 "The data is invalid" but you no longer have any return on the form with the display of errors...

Something had to change between laravel 5.4 and 5.7 and I can't find what

**Comment by mjamroz** [comment]
no problem, climbing season!

so i installed fresh oblyk @ my localhost
and i got error described here: https://github.com/jeremykenedy/laravel-auth/issues/200

>  Undefined variable: subcopy 

after removing subcopy from `resources/views/vendor/mail/html/layout.blade.php`
problem dissapeared and i was able to create an account

btw - even with this error, accounts were created (stored to DB) properly.


I see that in oblyk prod. version new users appears :

> Last registered climbers
> woodiskingser
> Indéfini, ? ans arrivé le 18 Apr 2019
> BaptB
> Indéfini, 31 ans arrivé le 18 Apr 2019

then i bet problem is with creating mail templates, not with validation.

PS if it wont help (removing/fixing "subcopy") maybe try to recreate application key as well

**Comment by lucien-chastan** [comment]
Ok, in fresh installation we have a problem with subcopy, but in production, but in production I don't have this problem (probably I still have some songs from version 5.5 of laravel...)

But, if you try to create a new user with the same name, you will have a problem "Whoops: The given data was invalid" and not a return to the form with the message "The name is already taken"

**Comment by mjamroz** [comment]
ok, try modify:
Http/Controllers/Auth/RegisterController.php
adding
```
use Illuminate\Auth\Events\Registered; 
use Illuminate\Http\Request;
public function register(Request $request)
    {
        try{
            $this->validator($request->all())->validate();
        } catch (\Illuminate\Validation\ValidationException $e) { 
            return redirect('register')->withErrors($e->validator); 
        }

        event(new Registered($user = $this->create($request->all())));

        $this->guard()->login($user);

        return $this->registered($request, $user)
                        ?: redirect($this->redirectPath());
    }

```

**Comment by lucien-chastan** [comment]
Thank you!

Is fixed
