### ISSUE TITLE
Vertical Art Rungis : Informations contact erronées

### ISSUE THREAD

**Issue by bapinaud** [lucien-chastan/oblyk#80]
Bonjour,

Ma ligne directe de travail (0184256611) est affiché sur cette page : https://www.oblyk.org/fr/salle-escalade/166/verticalart-rungis

Pouvez-vous voir avec l'entreprise Vertical Art de Rungis pour mettre à jour le téléphone affiché svp, car je me fais actuellement spammer.

Merci pour votre compréhension :)

**Comment by lucien-chastan** [comment]
Bonjour Bapinaud

Toutes mes excuses pour cette erreur de numéro
C'est changé

Bonne journée

**Comment by bapinaud** [comment]
Merci pour cette réactivité !
